-- debug notifications:
-- os.execute(
-- 	"notify-send 'Window info' 'App: "
-- 		.. get_application_name()
-- 		.. "\nClass: "
-- 		.. get_class_instance_name()
-- 		.. "\nTitle: "
-- 		.. get_window_name()
-- 		.. "'"
-- )
