# Grayscale Theme
background            #080808
foreground            #ffffff
cursor                #eeeeee
cursor_text_color     #080808
selection_background  #444444
selection_foreground  #eeeeee

color0                #080808
color1                #6c4f4f
color2                #bcbcbc
color3                #444444
color4                #4e4e4e
color5                #585858
color6                #666666
color7                #767676

color8                #808080
color9                #8a8a8a
color10               #949494
color11               #9e9e9e
color12               #a8a8a8
color13               #b2b2b2
color14               #bcbcbc
color15               #eeeeee
